# This is a basic workflow to help you get started with Actions
name: My-GitHubActions-Basics

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello, world FROM testing job!"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
